# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run. 
on:
  pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
      - run: cd auth
      - run: npm install
      - run: npm run test:ci
