name: tests

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test:ci
